# Application name and server port
spring:
  application:
    name: Auth
  datasource:
    url: jdbc:postgresql://localhost:5432/TaskBoardPro
    username: postgres
    password: 0
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


# Server Configuration
server:
  port: 8443

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework.data: DEBUG  # Set Spring Data MongoDB log level to debug
    # You can set other specific package log levels similarly
# JWT configuration

# JWT configuration
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007a
    issuer: Book Store API


